# This file contains additional role imports, which extends the default deployment setup
# They can be removed in your individual setup if not needed
# You can also add your own custom role as shown in the example "apache_proxy"

# *** OPTIONAL CLOUD ***
#- { import_role: { name: wireguard_cloud }, tags: [ 'wireguard', 'wireguard_cloud', 'alpine' ] } 
#- { import_role: { name: cloud_nfs }, tags: [ 'cloud_nfs', 'alpine' ] }
#- { import_role: { name: cloud_mosquitto }, tags: [ 'cloud_mosquitto', 'alpine' ] }     # [docker,user:1883]
#- { import_role: { name: cloud_check }, tags: [ 'cloud_check', 'alpine' ] }

#- { import_role: { name: backup_cloud }, tags: [ 'cloud_backup', 'backup_cloud' ], vars: { cloud_backup_sync_target_path: "{{cloud_path}}remote/<client1>/", cloud_backup_name: "client1" } }

- { import_role: { name: weather_service }, tags: [ 'weather_service', 'alpine' ], vars: { publish_topic: "{{server_name}}", "use_cloud_mosquitto": no } }
#- { import_role: { name: weather_service }, tags: [ 'weather_service', 'alpine' ], vars: { publish_topic: "{{server_name}}", "use_cloud_mosquitto": yes } } # cloud enabled weather provider
#- { import_role: { name: weather_service }, tags: [ 'weather_service', 'alpine' ], vars: { publish_topic: no, "use_cloud_mosquitto": yes } } # cloud enabled weather consumer

# *** OPTIONAL OTHERS ***
- { import_role: { name: vcontrold }, tags: [ 'vcontrold', 'alpine' ] }                  # heating control for viessmann vitodens            [docker,user:nobody|dialout]

- { import_role: { name: "config/jupiter/roles/menuentries" }, tags: [ 'menuentries' ] }    # additional menuentries for external devices

- { import_role: { name: ci_service }, tags: [ 'ci_service' ] }                         # continues integration test service

#- { import_role: { name: update_notifier }, tags: [ 'update_notifier' ] }               # update check for installed software
- { import_role: { name: "config/jupiter/roles/hosts" }, tags: [ 'hosts' ] }                # add local host names/IPs to DNS 
#- { import_role: { name: "config/jupiter/roles/asterisk" }, tags: [ 'asterisk' ] }          # asterisk SIP server
- { import_role: { name: "config/jupiter/roles/zigbee2mqtt" }, tags: [ 'zigbee2mqtt' ] }    # configuration of zigbee2mqtt
#- { import_role: { name: "config/jupiter/roles/recorder" }, tags: [ 'recorder' ] }          # configuration of OwnTracks Recorder
#- { import_role: { name: "config/jupiter/roles/flexisip" }, tags: [ 'flexisip' ] }          
- { import_role: { name: "config/jupiter/roles/unifi" }, tags: [ 'unifi' ] }
- { import_role: { name: "config/jupiter/roles/mytracker" }, tags: [ 'mytracker' ] }
- { import_role: { name: "config/jupiter/roles/hikvision" }, tags: [ 'hikvision' ] }
- { import_role: { name: "config/jupiter/roles/snapcast" }, tags: [ 'snapcast' ] }
#- { import_role: { name: "config/jupiter/roles/homeassistant" }, tags: [ 'homeassistant' ] }
- { import_role: { name: "config/jupiter/roles/mimic3" }, tags: [ 'mimic3' ] }
- { import_role: { name: "config/jupiter/roles/rsyncd" }, tags: [ 'rsyncd' ] }
- { import_role: { name: "config/jupiter/roles/fireflyiii" }, tags: [ 'fireflyiii' ] }
- { import_role: { name: "config/jupiter/roles/ghostfolio" }, tags: [ 'ghostfolio' ] }