# This file contains additional role imports, which extends the default deployment setup
# They can be removed in your individual setup if not needed
# You can also add your own custom role as shown in the example "apache_proxy"

# *** OPTIONAL CLOUD ***
#- { import_role: { name: wireguard_cloud }, tags: [ 'wireguard', 'wireguard_cloud', 'alpine' ] }
#- { import_role: { name: cloud_nfs }, tags: [ 'cloud_nfs', 'alpine' ] }
#- { import_role: { name: cloud_mosquitto }, tags: [ 'cloud_mosquitto', 'alpine' ] }     # [docker,user:1883]
#- { import_role: { name: cloud_check }, tags: [ 'cloud_check', 'alpine' ] }

# *** OPTIONAL OTHERS ***
- { import_role: { name: vcontrold }, tags: [ 'vcontrold', 'alpine' ] }                  # heating control for viessmann vitodens            [docker,user:nobody|dialout]

#- { import_role: { name: openwrt }, tags: [ 'openwrt' ] }                               # openwrt config generator
#- { import_role: { name: ci_service }, tags: [ 'ci_service' ] }                         # continues integration test service

- { import_role: { name: "config/jupiter/roles/menuentries" }, tags: [ 'menuentries' ] } # additional menuentries for external devices

- { import_role: { name: "config/jupiter/roles/hosts" }, tags: [ 'hosts' ] }             # local firewalls rules
- { import_role: { name: "config/jupiter/roles/zigbee2mqtt" }, tags: [ 'zigbee2mqtt' ] } # configuration of zigbee2mqtt        
- { import_role: { name: "config/jupiter/roles/unifi" }, tags: [ 'unifi' ] }
- { import_role: { name: "config/jupiter/roles/mytracker" }, tags: [ 'mytracker' ] }
- { import_role: { name: "config/jupiter/roles/hikvision" }, tags: [ 'hikvision' ] }
- { import_role: { name: "config/jupiter/roles/snapcast" }, tags: [ 'snapcast' ] }
- { import_role: { name: "config/jupiter/roles/mimic3" }, tags: [ 'mimic3' ] }
- { import_role: { name: "config/jupiter/roles/rsyncd" }, tags: [ 'rsyncd' ] }
- { import_role: { name: "config/jupiter/roles/fireflyiii" }, tags: [ 'fireflyiii' ] }
- { import_role: { name: "config/jupiter/roles/ghostfolio" }, tags: [ 'ghostfolio' ] }
- { import_role: { name: "config/jupiter/roles/vdirsyncer" }, tags: [ 'vdirsyncer' ] }
- { import_role: { name: "config/jupiter/roles/pigallery2" }, tags: [ 'pigallery2' ] }
#NICETOHAVE- { import_role: { name: "config/jupiter/roles/jekyll" }, tags: [ 'jekyll' ] }
#NICETOHAVE- { import_role: { name: "config/jupiter/roles/hugo" }, tags: [ 'hugo' ] }