- name: restart screenoff
  systemd:
    name: screenoff
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: no
  listen: "restart screenoff"

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: no
  listen: "restart rsyslog"
  
- name: restart sport_sync
  systemd:
    name: sport_sync
    state: restarted
    daemon_reload: yes
    enabled: yes
    masked: no
  listen: "restart sport_sync"