- name: "create systemd service"
  template:
    src: "templates/etc/systemd/system/screenoff.service"
    dest: "/etc/systemd/system/screenoff.service"
    owner: root
    group: root
    mode: 0644
  notify: "restart screenoff"

- name: privileged vpn clients
  set_fact:
    vpn_privileged_ips: |
      [      
      "{{userdata['alina'].vpn_gates['phone']}}",
      "{{userdata['alina'].vpn_gates['laptop']}}",
      "{{userdata['alina'].vpn_gates['tablet']}}"
      ]
  tags: [ 'user', 'firewall_config' ]

- name: specific to my installation firewall rules
  vars:
    service_name: "jupiter"
    container_to_outside_rules: |
      [
          { "saddr": {{ vpn_privileged_ips | to_json}}, "comment": "VPN clients access local network" }
      ]
    network_to_host_rules:
      - { protocol: "udp", dport: "46000", comment: "fineoffsetweatherstation openHAB binding discovery port" }
      - { protocol: "udp", dport: "54321", comment: "miio openHAB binding discovery port" }
  include_tasks: roles/firewall/shared/allow_service.yml
  tags: ['firewall_config']