- name: "create systemd service"
  template:
    src: "templates/etc/systemd/system/sport_sync.service"
    dest: "/etc/systemd/system/sport_sync.service"
    owner: root
    group: root
    mode: 0644
  notify: "restart sport_sync"
  
- name: "create systemd timer"
  template:
    src: "templates/etc/systemd/system/sport_sync.timer"
    dest: "/etc/systemd/system/sport_sync.timer"
    owner: root
    group: root
    mode: 0644
  notify: "restart sport_sync"
  
- name: Enable and start the sport_sync timer
  ansible.builtin.systemd:
    name: sport_sync.timer
    enabled: true
    state: started