{
 "title": "Heating",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "Outside temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Outside temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Outdoor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outside temperature subdued",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Outdoor_Subdued",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Interior room temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Technical room",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature_B_Technicalroom",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Livingroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature_GF_Livingroom",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Kitchen",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature_GF_Kitchen",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Hall",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature_GF_Hall",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Bedroom",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature_FF_Bedroom",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Bedroom Tudor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature_FF_RoomTudor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Bedroom Victor",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "Temperature_FF_RoomVictor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heating power",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Power",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Outside (current)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Outdoor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Outside (subdued)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Outdoor_Subdued",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Supply (target)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Offset_Target",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Supply (current)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Offset",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Return (current)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Return",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Water",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Wather_Storage",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Supply (sensor)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Pipe_Out",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Return (sensor)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Temperature_Pipe_In",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Heating circuit pump",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Heating pump",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Circuit_Pump_Speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Internal pump",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Circuit_PumpInternal_Speed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Burner starts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Burner starts",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Burner_Starts_Current_Daily",
     "query": "SELECT last(\"value\") FROM \"pGF_Utilityroom_Heating_Burner_Starts_Current_Daily\" WHERE $timeFilter GROUP BY time(1d) fill(none) tz('Europe/Bucharest')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Burner starts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Burner starts",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Burner_Starts_Current_Daily",
     "query": "SELECT last(\"value\") FROM \"pGF_Utilityroom_Heating_Burner_Starts_Current_Daily\" WHERE $timeFilter GROUP BY time(1d) fill(none) tz('Europe/Bucharest')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Burner runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "Burner runtime",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Burner_Hours_Current_Daily",
     "query": "SELECT last(\"value\") FROM \"pGF_Utilityroom_Heating_Burner_Hours_Current_Daily\" WHERE $timeFilter GROUP BY time(1d) fill(none) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Burner runtime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "h" }
   ],
   "targets": [
    {
     "alias": "Burner runtime",
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "pGF_Utilityroom_Heating_Burner_Hours_Current_Daily",
     "query": "SELECT last(\"value\") FROM \"pGF_Utilityroom_Heating_Burner_Hours_Current_Daily\" WHERE $timeFilter GROUP BY time(1d) fill(none) tz('Europe/Berlin')",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  }
 ]
}