- name: set version
  set_fact:
    zigbee2mqtt_version: "1.39.0"
  tags: [ 'update_notifier_config' ]
- name: prepare needed directories
  vars:
    directories:
      - { mode: "u=rwx,g=rx,o=", owner: "root", group: "root", path: "{{ global_etc }}zigbee2mqtt" }
      - { mode: "u=rwx,g=rx,o=", owner: "root", group: "root", path: "{{ global_log }}zigbee2mqtt" }
  include_tasks: roles/_shared/create_directories.yml

- name: copy config
  template:
    src: "templates/etc/zigbee2mqtt/{{item}}"
    dest: "{{ global_etc }}zigbee2mqtt/{{item}}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - "configuration.yaml"
    - "devices.yaml"
    - "groups.yaml"
  notify: "restart zigbee2mqtt"

- name: prepare published_ports
  set_fact:
    zigbee2mqtt_published_ports:  |
      [
        "8084:8084",
        {% if default_server_ipv6 is defined %}
          "[::]:8084:8084",
        {% endif %}
      ]
  tags: ['firewall_config']

- name: build podman image
  vars:
    container_name: "zigbee2mqtt"
    image_name: "custom_zigbee2mqtt"
    image_version: "{{zigbee2mqtt_version}}"
    image_files:
      - '{{config_path}}roles/zigbee2mqtt/templates/container/Dockerfile'
  include_tasks: roles/container/shared/build_podman_image.yml

- name: create podman container
  containers.podman.podman_container:
    name: zigbee2mqtt
    image: "custom_zigbee2mqtt:{{zigbee2mqtt_version}}"
    state: present
    security_opt:
      - label=disable
    env:
      TZ: "{{timezone}}"
    log_driver: journald
    log_options:
      tag: zigbee2mqtt
    network: "isolated"
    ip: "{{podman_zigbee2mqtt_ip}}"
    volumes:
      - '{{global_etc}}zigbee2mqtt:/app/data'
      - '{{global_log}}zigbee2mqtt:/app/data/log'
    published_ports: "{{zigbee2mqtt_published_ports}}"
  register: "podman_container_state"
  notify: "restart zigbee2mqtt"

# ***** SERVICE CONFIGS *****
- name: handle systemd service
  vars:
    container_name: "zigbee2mqtt"
    container_changed: "{{podman_container_state.changed}}"
    container_after: [ "mosquitto" ]
  include_tasks: roles/container/shared/handle_podman_service.yml
  tags: ['systemd_watcher_config']

- name: allow service
  vars:
    service_name: "zigbee2mqtt"
    nat_rules: { ip: "{{podman_zigbee2mqtt_ip}}", ports: "{{zigbee2mqtt_published_ports}}" }
    container_to_container_rules:
      - { saddr: "{{podman_zigbee2mqtt_ip}}", daddr: "{{podman_mosquitto_ip}}", protocol: "tcp", dport: "1883", comment: "zigbee2mqtt => mosquitto" }
    container_to_outside_rules:
      - { saddr: "{{podman_zigbee2mqtt_ip}}", daddr: "{{zigbee_adapter_ip}}", protocol: "tcp", dport: "6638", comment: "zigbee2mqtt => zigbee-adapter" }
  include_tasks: roles/firewall/shared/allow_service_nftables.yml
  tags: ['firewall_config']
  when: "nftables_enabled"

- name: allow service
  vars:
    firewall_name: "zigbee2mqtt"
    firewall_rules:
      - "saddr {{podman_zigbee2mqtt_ip}} daddr {{docker_mosquitto_ip}}"
      - "saddr {{podman_zigbee2mqtt_ip}} daddr {{zigbee_adapter_ip}}"
      - "saddr {{podman_zigbee2mqtt_ip}} proto tcp dport 443" # is this really needed?
  import_tasks: roles/firewall/shared/allow_service.yml
  tags: [ 'firewall_config' ]
  when: "not nftables_enabled"

- name: add service name
  vars:
    host_name: "zigbee2mqtt"
    host_ip_address: "{{podman_zigbee2mqtt_ip}}"
  include_tasks: roles/_shared/add_to_hosts.yml

# ***** FINALIZE *****
- name: register webui
  vars:
    name: "zigbee2mqtt"
    js_file: "templates/webui/zigbee2mqtt.js"
    icons: [ 'templates/webui/icons/zigbee2mqtt_logo.svg' ]
  include_tasks: roles/apache_webui/shared/add_webui.yml
  tags: ['apache_webui_config']

- name: copy apache vhost
  vars:
    sub_domain: "zigbee2mqtt"
    usergroup: "user"
    include: "templates/etc/apache2/_.ansible.vhost.d/zigbee2mqtt.inc"
  import_tasks: roles/apache/shared/add_vhost.yml
  tags: ['apache_config']

- name: register update notifier
  vars:
    name: "zigbee2mqtt"
    type: "github"
    url: "https://github.com/Koenkk/zigbee2mqtt/releases"
    config: { 
      project: "Koenkk/zigbee2mqtt", 
      pattern: "^([0-9\\.]+)$",
      version: "{{zigbee2mqtt_version}}" 
    }
  include_tasks: roles/update_service/shared/add_software.yml
  tags: ['update_notifier_config']
  when: "update_service_software_check_enabled"

- name: trigger zigbee2mqtt handler
  vars:
    notify: "restart zigbee2mqtt"
    service: "zigbee2mqtt.service"
  import_tasks: roles/_shared/service_check.yml

