- name: set version
  set_fact:
    zigbee2mqtt_version: "1.41.0"
  tags: [ 'update_notifier_config' ]

- name: prepare needed directories
  vars:
    directories:
      - { mode: "u=rwx,g=rx,o=", owner: "root", group: "root", path: "{{ global_etc }}zigbee2mqtt" }
      - { mode: "u=rwx,g=rx,o=", owner: "root", group: "root", path: "{{ global_log }}zigbee2mqtt" }
  include_tasks: roles/_shared/create_directories.yml

- name: copy config
  template:
    src: "templates/etc/zigbee2mqtt/{{item}}"
    dest: "{{ global_etc }}zigbee2mqtt/{{item}}"
    owner: root
    group: root
    mode: 0640
  with_items:
    - "configuration.yaml"
    - "devices.yaml"
    - "groups.yaml"
  notify: "restart zigbee2mqtt"

- name: build podman image
  vars:
    container_name: "zigbee2mqtt"
    image_name: "custom_zigbee2mqtt:{{zigbee2mqtt_version}}"
    image_files:
      - '{{config_path}}roles/zigbee2mqtt/templates/container/Dockerfile'
  include_tasks: roles/container/shared/build_podman_image.yml

- name: prepare published_ports
  set_fact:
    zigbee2mqtt_published_ports:  |
      [
        "8084:8084",
        {% if default_server_ipv6 is defined %}
          "[::]:8084:8084",
        {% endif %}
      ]
  tags: ['firewall_config']

- name: create container service
  vars:
    container_name: "zigbee2mqtt"
    container_image: "custom_zigbee2mqtt:{{zigbee2mqtt_version}}"
    container_network: "isolated"
    container_ip: "{{podman_zigbee2mqtt_ip}}"
    container_published_ports: "{{zigbee2mqtt_published_ports}}"
    container_env:
      TZ: "{{timezone}}"
    container_volumes: 
      - '{{global_etc}}zigbee2mqtt:/app/data'
      - '{{global_log}}zigbee2mqtt:/app/data/log'
    container_after: [ "mosquitto" ]
    container_readyness: { "type": "port_check", "ip": "{{podman_zigbee2mqtt_ip}}", "port": "8084" }
  include_tasks: roles/container/shared/create_podman_service.yml
  tags: ['podman_container','systemd_watcher_config','systemd_service_config']

- name: allow service
  vars:
    service_name: "zigbee2mqtt"
    nat_rules: { ip: "{{podman_zigbee2mqtt_ip}}", ports: "{{zigbee2mqtt_published_ports}}" }
    container_to_container_rules:
      - { saddr: "{{podman_zigbee2mqtt_ip}}", daddr: "{{podman_mosquitto_ip}}", protocol: "tcp", dport: "1883", comment: "zigbee2mqtt => mosquitto" }
    container_to_outside_rules:
      - { saddr: "{{podman_zigbee2mqtt_ip}}", daddr: "{{zigbee_adapter_ip}}", protocol: "tcp", dport: "6638", comment: "zigbee2mqtt => zigbee-adapter" }
      - { saddr: "{{podman_zigbee2mqtt_ip}}", protocol: "tcp", dport: "443", oif: "{{default_network_interface}}", comment: "zigbee2mqtt => external - OTA update checks" }
  include_tasks: roles/firewall/shared/allow_service.yml
  tags: ['firewall_config']

- name: add service name
  vars:
    host_name: "zigbee2mqtt"
    host_ip_address: "{{podman_zigbee2mqtt_ip}}"
  include_tasks: roles/_shared/add_to_hosts.yml

# ***** FINALIZE *****
- name: register webui
  vars:
    name: "zigbee2mqtt"
    js_file: "templates/webui/zigbee2mqtt.js"
    icons: [ 'templates/webui/icons/zigbee2mqtt_logo.svg' ]
  include_tasks: roles/apache_webui/shared/add_webui.yml
  tags: ['apache_webui_config']

- name: copy apache vhost
  vars:
    sub_domain: "zigbee2mqtt"
    usergroup: "user"
    include: "templates/etc/apache2/_.ansible.vhost.d/zigbee2mqtt.inc"
  include_tasks: roles/apache/shared/add_vhost.yml
  tags: ['apache_config']

- name: register update notifier
  vars:
    name: "zigbee2mqtt"
    type: "github"
    url: "https://github.com/Koenkk/zigbee2mqtt/releases"
    config: { 
      project: "Koenkk/zigbee2mqtt", 
      pattern: "^([0-9\\.]+)$",
      version: "{{zigbee2mqtt_version}}" 
    }
  include_tasks: roles/update_service/shared/add_software.yml
  tags: ['update_notifier_config']
  when: "update_service_software_check_enabled"
