---

- name: restart pihole dns
  shell: pihole restartdns
  when: not running_as_container
  listen: "restart pihole dns"

- name: restart pihole docker
  shell: docker exec -t pihole pihole restartdns
  when: running_as_container
  listen: "restart pihole dns"