- name: set version
  set_fact:
    hikvision_doorbell_version: "3.0.22-amd64"
  tags: [ 'update_notifier_config' ]

- name: prepare needed directories
  vars:
    directories:
      - { mode: "u=rwx,g=rx,o=", owner: "root", group: "root", path: "{{global_etc}}hikvision_doorbell" }
  include_tasks: roles/_shared/create_directories.yml
    
- name: copy config
  template:
    src: "templates/etc/config.yml"
    dest: "{{global_etc}}hikvision_doorbell/config.yml"
    owner: "root"
    group: "root"
    mode: 0750
  notify: "restart hikvision_doorbell"

- name: create container service
  vars:
    container_name: "hikvision_doorbell"
    container_image: "pergolafabio/hikvision-doorbell:{{hikvision_doorbell_version}}"
    container_network: "host"
    container_no_healthcheck: yes
    container_env:
      CONFIG_FILE_PATH: "/etc/hikvision_doorbell/config.yml"
    container_volumes:
      - '{{global_etc}}hikvision_doorbell:/etc/hikvision_doorbell:ro'
    container_after: [ "mosquitto" ]
    container_readyness: { "type": "state_check" }
  include_tasks: roles/container/shared/create_podman_service.yml
  tags: ['podman_container','systemd_watcher_config','systemd_service_config']
  
# ***** DEPENDENCY CONFIGS *****
- name: register update notifier
  vars:
    name: "hikvision_doorbell"
    type: "docker"
    url: "https://hub.docker.com/r/pergolafabio/hikvision-doorbell"
    config: { 
      repository: "pergolafabio/hikvision-doorbell", 
      pattern: "^([0-9\\.]+)-amd64$"
    }
  include_tasks: roles/update_service/shared/add_software.yml
  tags: ['update_notifier_config']
  when: "update_service_software_check_enabled"
