- name: set snapcast version
  set_fact:
    snapcast_version: "0.32.1"
  tags: [ 'update_notifier_config' ]

- name: prepare needed folder
  file:
    path:  "{{item}}"
    state: directory
    owner: "root"
    group: "root"
    mode: 0750
  with_items:
    - "{{global_build}}snapcast"
    
- name: install required packages => is_suse
  zypper:
    name: [
        gcc12-c++
      , cmake-full
      , libboost_headers1_75_0-devel
      , libopenssl-devel
      , soxr-devel
      , alsa-devel
      , libpulse-devel
      , libvorbis-devel
      , flac-devel
      , libopus-devel
      , libavahi-devel
      , alsa-utils  
    ]
    state: present
  when: is_suse|bool
  
- name: "clone snapcast git"
  git:
    repo: 'https://github.com/badaix/snapcast'
    dest: '{{global_build}}snapcast'
    version: 'v{{snapcast_version}}'  
  register: snapcast_git
  
- name: "build snapcast client"
  shell: |
    mkdir build
    cd build
    cmake .. -DBUILD_CLIENT=ON -DBUILD_SERVER=OFF -DBUILD_WITH_PULSE=OFF -DBUILD_WITH_EXPAT=OFF
    cmake --build .
    install -s -D -g root -o root ../bin/snapclient /usr/bin/snapclient
    install -D -g root -o root ../client/snapclient.1 /usr/share/man/man1/snapclient.1
  args:
    chdir: "{{global_build}}snapcast"
  when: "snapcast_git.changed"
  
- name: copy files
  template:
    src: "templates{{item.path}}"
    dest: "{{item.path}}"
    owner: root
    group: root
    mode: "{{item.mode}}"
  with_items:
    - { mode: "u=rw,g=r,o=r", path: "/etc/systemd/system/snapclient.service" }
    - { mode: "u=rw,g=r,o=r", path: "/etc/default/snapclient.default" }

- name: "systemctl housekeeping"
  shell: |
    systemctl daemon-reload
    systemctl enable snapclient
    systemctl start snapclient  

# ***** FINALIZE *****
- name: register systemd service watcher
  vars:
    watcher_name: "snapclient"
  include_tasks: roles/systemd_watcher/shared/add_watcher.yml

- name: register update notifier
  vars:
    name: "snapcast"
    type: "github"
    url: "https://github.com/badaix/snapcast/releases"
    config: { 
      project: "badaix/snapcast", 
      pattern: "^v([0-9\\.]+)$",
      version: "v{{snapcast_version}}" 
    }
  include_tasks: roles/update_service/shared/add_software.yml
