- name: set version
  set_fact:
    mytracker_version: 'unknown'
  tags: [ 'update_notifier_config' ]
  
- name: prepare needed directories
  vars:
    directories:
      - { mode: "u=rwx,g=rx,o=", owner: "root", group: "root", path: "{{ global_etc }}mytracker" }
  include_tasks: roles/_shared/create_directories.yml

- name: build podman image
  vars:
    container_name: "mytracker"
    image_name: "custom_mytracker:{{alpine_version}}-{{mytracker_version}}"
    image_files:
      - "{{config_path}}/roles/mytracker/templates/container/Dockerfile"
  include_tasks: roles/container/shared/build_podman_image.yml

- name: create container service
  vars:
    container_name: "mytracker"
    container_image: "custom_mytracker:{{alpine_version}}-{{mytracker_version}}"
    container_network: "isolated"
    container_ip: "{{podman_mytracker_ip}}"
    container_exposed_ports:
      - "5000"
    container_env:
      TZ: "{{timezone}}"
      FLASK_ENV: "development"
      FLASK_DEBUG : "False"
    container_volumes: 
      - '{{global_lib}}mytracker/:/var/lib/mytracker'
    container_after: [ "mosquitto" ]
    container_readyness: { "type": "port_check", "ip": "{{podman_mytracker_ip}}", "port": "5000" }
  include_tasks: roles/container/shared/create_podman_service.yml
  tags: ['podman_container','systemd_watcher_config','systemd_service_config']

- name: allow service
  vars:
    service_name: "mytracker"
    container_to_container_rules:
      - { saddr: "{{podman_mytracker_ip}}", daddr: "{{podman_mosquitto_ip}}", protocol: "tcp", dport: "1883", comment: "mytracker => mosquitto" }
  include_tasks: roles/firewall/shared/allow_service.yml
  tags: ['firewall_config']

- name: add service name
  vars:
    host_name: "mytracker"
    host_ip_address: "{{podman_mytracker_ip}}"
  include_tasks: roles/_shared/add_to_hosts.yml

# ***** FINALIZE *****
- name: register webui
  vars:
    name: "mytracker"
    js_file: "templates/webui/mytracker.js"
    icons: [ 'templates/webui/icons/mytracker_logo.svg' ]
  include_tasks: roles/apache_webui/shared/add_webui.yml
  tags: ['apache_webui_config']

- name: copy apache config
  vars:
    config_file: "templates/etc/apache2/_.ansible.conf.d/mytracker.conf"
  import_tasks: roles/apache/shared/add_config.yml
