- name: "disable: copy resolv.conf (external)"
  vars:
    local_resolv_server: "{{router_ip}}"
  template:
    src: templates/resolv.conf
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0755
