- name: set version
  set_fact:
    ghostfolio_version: '2.197.0'
  tags: [ 'update_notifier_config' ]

- name: create container service
  vars:
    container_name: "ghostfolio"
    container_image: "ghostfolio/ghostfolio:{{ghostfolio_version}}"
    container_network: "isolated"
    container_ip: "{{podman_ghostfolio_ip}}"
    container_exposed_ports:
      - "3333"
    container_env:
      TZ: "UTC"
      ACCESS_TOKEN_SALT: "{{ghostfolio_token_salt}}"
      POSTGRES_DB: "ghostfolio"
      POSTGRES_USER: "{{ghostfolio_postgres_username}}"
      POSTGRES_PASSWORD: "{{ghostfolio_postgres_password}}"
      DATABASE_URL: "postgresql://{{ghostfolio_postgres_username}}:{{ghostfolio_postgres_password}}@postgres:5432/{{ghostfolio_postgres_db}}?connect_timeout=300&sslmode=prefer"
      JWT_SECRET_KEY: "{{ghostfolio_jwt_key}}"
      REDIS_HOST: "redis"
      REDIS_PORT: "6379"
    container_after: [ "postgres" ]
    container_readyness: { "type": "port_check", "ip": "{{podman_ghostfolio_ip}}", "port": "3333" }
  include_tasks: roles/container/shared/create_podman_service.yml
  tags: ['podman_container','systemd_watcher_config','systemd_service_config']

- name: allow service
  vars:
    service_name: "ghostfolio"
    container_to_container_rules:
      - { saddr: "{{podman_ghostfolio_ip}}", daddr: "{{podman_postgres_ip}}", protocol: "tcp", dport: "5432", comment: "ghostfolio => postgres" }
      - { saddr: "{{podman_ghostfolio_ip}}", daddr: "{{podman_redis_ip}}", protocol: "tcp", dport: "6379", comment: "ghostfolio => redis" }
    container_to_outside_rules:
      - { saddr: "{{podman_ghostfolio_ip}}", protocol: "tcp", dport: "443", oif: "{{default_network_interface}}", comment: "ghostfolio => external - Yahoo Finance" }
  include_tasks: roles/firewall/shared/allow_service.yml
  tags: ['firewall_config']

- name: add service name
  vars:
    host_name: "ghostfolio"
    host_ip_address: "{{podman_ghostfolio_ip}}"
  include_tasks: roles/_shared/add_to_hosts.yml

- name: create database
  vars:
    database: "{{ghostfolio_postgres_db}}"
    username: "{{ghostfolio_postgres_username}}"
    password: "{{ghostfolio_postgres_password}}"
    backup: yes
  include_tasks: roles/postgres/shared/add_database.yml
  tags: ['cron_job','backup_restore']
  when: "postgres_enabled"
  
# ***** FINALIZE *****
- name: register webui
  vars:
    name: "ghostfolio"
    js_file: "templates/webui/ghostfolio.js"
    icons: [ 'templates/webui/icons/ghostfolio_logo.svg' ]
  include_tasks: roles/apache_webui/shared/add_webui.yml
  tags: ['apache_webui_config']

- name: copy apache vhost
  vars:
    sub_domain: "ghostfolio"
    usergroup: "user"
    include: "templates/etc/apache2/_.ansible.vhost.d/ghostfolio.inc"
  include_tasks: roles/apache/shared/add_vhost.yml
  tags: ['apache_config']

- name: copy fluentd config
  vars:
    config_file: "templates/etc/fluent/_.ansible.d/ghostfolio.conf"
  include_tasks: roles/fluentd/shared/add_config.yml
  tags: ['fluentd_config']
  when: "monitoring_enabled"
  
- name: register update notifier
  vars:
    name: "ghostfolio"
    type: "docker"
    url: "https://github.com/ghostfolio/ghostfolio/releases"
    config: {
      repository: "ghostfolio/ghostfolio",
      pattern: "^([0-9\\.]+)$"
    }
  include_tasks: roles/update_service/shared/add_software.yml
  tags: ['update_notifier_config']
  when: "update_service_software_check_enabled"