version: 4
# Home Assistant integration (MQTT discovery)
homeassistant:
  enabled: false

# MQTT settings
mqtt:
  # MQTT base topic for zigbee2mqtt MQTT messages
  base_topic: zigbee2mqtt
  # MQTT server URL
  server: mqtt://mosquitto

# Serial settings
serial:
  # Location of CC2531 USB sniffer
  #port: /dev/ttyOpenHabZigbee

  # Location of SLZB-06
  port: tcp://{{zigbee_adapter_ip}}:6638
  baudrate: 115200
  adapter: zstack
  # Disable green led?
  disable_led: false
  
# Set output power to max 20
advanced:
  transmit_power: 20

devices: devices.yaml

frontend:
  enabled: true
  # Optional, default 8080
  port: 8084
  # Optional, default 0.0.0.0
  host: 0.0.0.0
  # Optional, enables authentication, disabled by default
  #auth_token: blabla